import type { Metadata } from "next";
import { FooterLayout } from "./_layout/Footer";
import { HeaderLayout } from "./_layout/Header";
import "./globals.css";
import { PTContainer } from "./_commons/_components/PTContainer";
import { PTGrid } from "./_commons/_components";
import { Grid } from "@mui/material";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        <PTContainer>
          <PTGrid>
            <Grid md={10}>
              {children}
            </Grid>
          </PTGrid>
        </PTContainer>
        <FooterLayout />
      </body>
    </html>
  );
}
