import type { Metadata } from "next";
import { FooterLayout } from "./_layout/Footer";
import { HeaderLayout } from "./_layout/Header";
import "./globals.css";
import { PTContainer, PTGridContainer } from "./_components/_commons";
import { Grid } from "@mui/material";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        <PTContainer>
          <PTGridContainer>
              {children}
          </PTGridContainer>
        </PTContainer>
        <FooterLayout />
      </body>
    </html>
  );
}
