import type { Metadata } from "next";
import { FooterLayout } from "./_layout/FooterLayout";
import { HeaderLayout } from "./_layout/Header";
import "./globals.css";
import { PTContainer } from "./_commons/_components/PTContainer";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        <PTContainer>
          {children}
        </PTContainer>
        <FooterLayout />
      </body>
    </html>
  );
}
