import { Metadata } from 'next';
import { PersonalInfo } from './_components/PersonalInfo';
import { Skills } from './_components/Skills';

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <PersonalInfo />
      <Skills />
    </>
  );
}

